investors_columns = {
        '證券代號': 'stock_id',
        '證券名稱': 'stock_name',
        '外資買進股數': 'foreign_buy',
        '外資賣出股數': 'foreign_sell',
        '外資買賣超股數': 'foreign_net_buy',
        '自營商買進股數': 'dealer_buy',
        '自營商賣出股數': 'dealer_sell',
        '外陸資買進股數(不含外資自營商)': 'foreign_buy_excluding_dealers',
        '外陸資賣出股數(不含外資自營商)': 'foreign_sell_excluding_dealers',
        '外陸資買賣超股數(不含外資自營商)': 'foreign_net_buy_excluding_dealers',
        '外資自營商買進股數': 'dealer_foreign_buy',
        '外資自營商賣出股數': 'dealer_foreign_sell',
        '外資自營商買賣超股數': 'dealer_foreign_net_buy',
        '投信買進股數': 'investment_trust_buy',
        '投信賣出股數': 'investment_trust_sell',
        '投信買賣超股數': 'investment_trust_net_buy',
        '自營商買賣超股數': 'dealer_net_buy',
        '自營商買進股數(自行買賣)': 'dealer_self_buy',
        '自營商賣出股數(自行買賣)': 'dealer_self_sell',
        '自營商買賣超股數(自行買賣)': 'dealer_self_net_buy',
        '自營商買進股數(避險)': 'dealer_hedge_buy',
        '自營商賣出股數(避險)': 'dealer_hedge_sell',
        '自營商買賣超股數(避險)': 'dealer_hedge_net_buy',
        '三大法人買賣超股數': 'total_institution_net_buy'
    }